# -*- coding: utf-8 -*-
"""EcoCycle-AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-fFEIDNspIH0Z8IPAhjQi10MW46H7G9
"""

import os
from zipfile import ZipFile

# Folder name
project_name = "ecocycle-ai"
os.makedirs(f"{project_name}/src", exist_ok=True)

# 1. App.js
with open(f"{project_name}/src/App.js", "w") as f:
    f.write('''import EcoCycleAI from "./EcoCycleAI";
export default EcoCycleAI;
''')

# 2. EcoCycleAI.js (short version for now)
with open(f"{project_name}/src/EcoCycleAI.js", "w") as f:
    f.write('''import { useState } from "react";
import { Moon, Sun } from "lucide-react";

export default function EcoCycleAI() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <div className="min-h-screen bg-white dark:bg-gray-900 text-gray-900 dark:text-white transition-colors duration-300">
        <nav className="flex justify-between items-center p-6 shadow-md bg-gray-100 dark:bg-gray-800">
          <h1 className="text-2xl font-bold">EcoCycle-AI</h1>
          <div className="flex items-center gap-4">
            <a href="#features">Features</a>
            <a href="#how-it-works">How It Works</a>
            <a href="#contact">Contact</a>
            <button onClick={() => setDarkMode(!darkMode)}>
              {darkMode ? <Sun /> : <Moon />}
            </button>
          </div>
        </nav>
        <section className="text-center py-20 px-6">
          <h2 className="text-4xl font-bold mb-4">Smarter Rides with EcoCycle-AI</h2>
          <p className="text-lg mb-6">AI-powered cycle sharing for all, including differently-abled users.</p>
          <button className="bg-green-600 text-white px-6 py-3 rounded-xl">Book a Cycle</button>
        </section>
      </div>
    </div>
  );
}
''')

# 3. index.css (for Tailwind)
with open(f"{project_name}/src/index.css", "w") as f:
    f.write('''@tailwind base;
@tailwind components;
@tailwind utilities;
''')

# 4. tailwind.config.js
with open(f"{project_name}/tailwind.config.js", "w") as f:
    f.write('''module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: { extend: {} },
  plugins: [],
}
''')

# 5. postcss.config.js
with open(f"{project_name}/postcss.config.js", "w") as f:
    f.write('''module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
''')

# 6. Zip the folder
zip_path = f"{project_name}.zip"
with ZipFile(zip_path, 'w') as zipf:
    for foldername, subfolders, filenames in os.walk(project_name):
        for filename in filenames:
            filepath = os.path.join(foldername, filename)
            zipf.write(filepath)

# Show download link
from IPython.display import FileLink
FileLink(zip_path)